### ISSUE TITLE
About remote connections

### ISSUE THREAD

**Issue by magefesa** [alexp2ad/homebridge-plex-sensors#12]
Hi ! Great great Plugin ! Thanks a lot for your efforts ! 
I have a little problem... If i run the plex movie/tvShow from home, any problem, all works like a charm. The problkem is if i m seeing a show from another location... the webhook acts, and my homekit setup is ok, i ve checked the option " When I m at home", but does not matter, the Webhook acts and my wife does nt like it soo much :-)

Any ideas please ?
![ios](https://user-images.githubusercontent.com/84852/44239743-1b133500-a1bb-11e8-99e6-812e6981a06f.jpg)

**Comment by alexjsp** [comment]
The way I handle this is using sensors specific to players, so I have a sensor for my Living Room Apple TV that only triggers for those playbacks, and playbacks from (eg. my iPad) are ignored.

If you want to be triggered by playbacks from something like an iPad but only when it's at home, that gets trickier, you _might_ be able to detect that with a custom filter like:

```
"sensors": [
      {
        "name": "Player at Home",
        "customFilters":
        {
          "Player.local": true
        }
      }
```

But I haven't tested that. I might look into integrating that properly as a `localPlayerOnly` option or something though if it works.

**Comment by magefesa** [comment]
I wnat exactly this ! only sensor to my apple tv ...how can i do that ?

**Comment by alexjsp** [comment]
@magefesa Have a look at the `players` setting on a sensor mentioned in the README. eg:

```
    "sensors": [
      {
        "name": "Movie Playing",
        "types": ["movie"],
        "players": ["Living Room"]
      }
```

That example will only trigger for a movie playing on a player called "Living Room", which is what my Apple TV is called. As the README says:

> To find out your player name you can check the [Now Playing section of Plex Web](https://app.plex.tv/desktop#!/status/playing)

**Comment by alexjsp** [comment]
(For Apple TV Plex uses whatever name is set in Apple TV System Settings -> General -> About -> Name)

**Comment by magefesa** [comment]
I m gonna try  it !! Thanks !!! I love you !!

**Comment by magefesa** [comment]
Works like a charm ! 
Perfect ... Just amazing sensor. Thanks a lot Alex.
