### ISSUE TITLE
plex sensor clears trigger even when ignore set to true

### ISSUE THREAD

**Issue by pslogic** [alexp2ad/homebridge-plex-sensors#13]
here is the relevant snippet of my 'config.json'

```
        {
            "platform": "homebridge-plex-sensors.Plex",
            "logSeenPlayersAndUsers": true,
            "ignorePauseResume": true,
            "sensors": [
                {
                    "name": "Media Playing"
                }
            ]
        },
```

when using the web client or PMP, the trigger clears even though `ignorePauseResume` is set to `true` and a video is paused

is anyone else experiencing this?

**Comment by pslogic** [comment]
@alexp2ad can you advise some troubleshooting tips?

**Comment by alexjsp** [comment]
@pslogic The `ignorePauseResume` setting is a per-sensor setting, so for your config you'd set it like this:

```
        {
            "platform": "homebridge-plex-sensors.Plex",
            "logSeenPlayersAndUsers": true,
            "sensors": [
                {
                    "name": "Media Playing",
                    "ignorePauseResume": true
                }
            ]
        },
```

Closing this issue, but feel free to re-open if you see the same issue.

**Comment by pslogic** [comment]
thanks! 👍
