### ISSUE TITLE
sensor triggering for all players.

### ISSUE THREAD

**Issue by Faintfuzzy** [alexp2ad/homebridge-plex-sensors#17]
Hi,
I have setup a very basic sensor which should trigger when a single player on my ATV is used.  I've tried using the player name and also the UUID, but every player in the house seems to trigger it.
        {
            "platform": "homebridge-plex-sensors.Plex",
            "logSeenPlayersAndUsers": true,
            "delayOff": 0,
            "sensors": [
                {
                    "name": "Plex Playing",
                    "player": "Living Room"
                }
            ]

I've also tried removing the player definition and seeing if I could trigger it based on plex user,  but again it seems to trigger on irrespective of which user tag is used.  Logging from homebridge is showing the correct tags coming in.

i'm at a loss as to how to get the sensor to trigger selectively and any help would be much appreciated.

Thanks

**Comment by alexjsp** [comment]
Hi, looks like you’re using `player` instead of `players` and passing a string instead of an array, so you should replace the player line in your post with:

`"players": ["Living Room"],`

Have a look at the examples in the README which should point you in the right direction.

**Comment by Faintfuzzy** [comment]
Thanks so much,  I thought I was doing something stupid and it turns out I was right.  Thanks for a great plugin and the help.
