### ISSUE TITLE
Webhook Delay

### ISSUE THREAD

**Issue by ryanschmidt** [alexp2ad/homebridge-plex-sensors#4]
Is it normal to see a 3-5 second delay on the webhook response? I was using another npm package that polls the server but then found this which makes a lot more sense (webhook vs polling). Before I try something else, I was just curious if the webhook delay was common since this is my first time using them for anything. I am running Homebridge on a different machine than Plex. Could that be the issue?

**Comment by QandnotU** [comment]
@ryanschmidt my response is instant, so the webhook is defiantly a faster solution than polling, don't have much insight on what might be the culprit in causing your delay.

**Comment by alexjsp** [comment]
Yeah, I'm not sure what would be causing that, it's pretty much instant for me (even when on different machines).  Are the two machines on the same network? And are you using a local IP address for the webhook in the Plex settings?  And what client are you using?

**Comment by ryanschmidt** [comment]
Hey guys! Sorry for not reporting back sooner. My delay is maybe 1-2 seconds and I don't even notice it anymore. Thanks for the great little utility!
