### ISSUE TITLE
Two or more players?

### ISSUE THREAD

**Issue by lespatots** [alexp2ad/homebridge-plex-sensors#6]
I have two TV players (and of course IOS etc). I do not get notifications or updates for the second player I created in the config. I notice that there was a similar issue in one of the other plex plug-ins and wondered whether this could be the same?
"platform": "homebridge-plex-sensors.Plex",
            "sensors": [
                {
                    "name": "Plex Playing Lounge",
                    "players": [
                        "TV UE65H6400"
                    ]
                },
                {
                    "name": "Plex Playing Bedroom",
                    "players": [
                        "Plex for LG"
                    ]
                }
            ]

Quick update. I added a new player, Firefox, which is on my Mac and that one works. It is just the LG TV, which I can get round I think by using the LG TV interface!

**Comment by alexjsp** [comment]
It should definitely work with multiple players (and I guess does with your Firefox player as you discovered)

It could be that you've got the name subtly wrong for the player, or that the LG client isn't sending the correct timeline events to the Plex Media Server to trigger the webhooks.

Try creating a generic "Plex Playing" sensor with no players (like the [first example in the README](https://github.com/alexp2ad/homebridge-plex-sensors#example-configs)) which should be triggered by ANY Plex playback and see if that sensor is triggered by the LG client.

**Comment by lespatots** [comment]
Hi,

It works as you suggest with no device specified. I copy/pasted the "Plex for LG" string from the Plex Devices screen which updates when a Plex device is used. Still no report. I haven't looked at the code but I guess it might be possible to output the device name that is found to a debug.

In fact, would it be possible for the code to create config entries for new devices it found if no name was specified? With of course an option setting to do that task.

**Comment by alexjsp** [comment]
Hey, definitely sounds like the device name isn't matching correctly.

I don't think it's possible for plugins to make changes to your config file, but instead I've added a setting `logSeenPlayersAndUsers` you can add to your config, that will print out the name of players and users as the plugin encounters them, so try adding that to your config (I've added an example config, it's the [last one in the README](https://github.com/alexp2ad/homebridge-plex-sensors#example-configs)) and then watch the Homebridge log when starting a playback from the LG and you should see something like:

```
[7/2/2018, 2:03:17 PM] [homebridge-plex-sensors.Plex] Seen player: "Plex for LG"
```

Except `Plex for LG` will be something subtly different, hopefully!

**Comment by Garywoo** [comment]
Thanks Alex,
This setting has also helped me get up and running as I was misunderstanding the device names, and didn’t have server access to check.

**Comment by lespatots** [comment]
Hi,

Thanks for that, here is the result:

[2018-7-3 09:29:52] [homebridge-plex-sensors.Plex] Seen player: ""
[2018-7-3 09:29:52] [homebridge-plex-sensors.Plex] Seen user: “rjstott"

So the LG is not very helpful sending a null string (not subtle) but this is what Plex tells me on the Devices screen:
"Plex for LG
12 minutes ago
3.13.22
Plex for LG"

How does Plex know something different?

I’m sure you’re right that plug-ins can’t change things (at least not in the Config file). The Hue plugin is somewhat similar in that you get the ‘password’ and have to add it manually into the config. Home Assistant (which continues to disappoint) gets around this (I think) by having small private files belonging to the plugin pointed to by the config. Wonder whether this is worth suggesting somewhere?

Thx

**Comment by alexjsp** [comment]
Interesting, it looks like the LG client just sends no name, as you suggest, and then Plex probably falls back to displaying the device's platform name which isn't sent to webhooks, so I can't use that here.

But, all hope isn't necessarily lost (yet 😛). Every player _should_ have a UUID (a unique identifier) that's sent with the webhook, so let's see if we get one of those for the LG.

I've pushed a new version that also logs the player's UUID, and allows you to filter events with that in the same way you can filter by player name.

Try grabbing the latest version and look in the logs for the UUID:

```
Seen player: "Plex for LG" (with UUID: "XXXXXX-XXXX-XXXX")
```

And hopefully unlike the name there'll be something there for the UUID. 😆 

If there is you can try adding it to a sensor in the same place you'd add a name, eg:

```
{
   "name": "Plex Playing Bedroom",
   "players": [
      "XXXXXX-XXXX-XXXX"
   ]
}
```

🤞 Hopefully it'll give us a UUID... 🤞

**Comment by lespatots** [comment]
Well, I went to try this immediately and Sod’s law came into play. At present Plex.tv <http://plex.tv/> has a ‘major outage’ so I can’t run the TV app but I will as soon as I can and report back!!

**Comment by alexjsp** [comment]
Definite sod's law in action.

I _think_ it's actually back already for me. 🤞

**Comment by lespatots** [comment]
Ok, it was back and:

[2018-7-3 10:50:49] [homebridge-plex-sensors.Plex] Seen player: "" (with UUID: "y1sgehh11vbcsorwkr04vlay")
[2018-7-3 10:50:49] [homebridge-plex-sensors.Plex] Seen user: “rjstott"

I’ll try the UUID shortly in the config, hopefully today.

The purpose of this was of course to dim appropriate lighting.

**Comment by alexjsp** [comment]
@lespatots Did you have success using the UUID of the device?

I'm gonna close this issue as I consider it resolved, but feel free to re-open if you still have issues.
