### ISSUE TITLE
Show current media

### ISSUE THREAD

**Issue by hazcod** [alexp2ad/homebridge-plex-sensors#8]
Would be cool if the plugin shows the current playing movie/series.

**Comment by alexjsp** [comment]
It's possible to add custom characteristics that would display that data in third party apps like [Home](https://itunes.apple.com/gb/app/home-smart-home-automation/id995994352?mt=8), but there's no good way that could be displayed in the official Apple Home app, so I'm not sure it's worth adding TBH.

(Also each sensor can theoretically be triggered by multiple playbacks, so it would be hard to know which to show)
